import React, {Component} from 'react';

import Back from '../Main/Back/container';

class Tribute extends React.Component {
  constructor(props) {
    super(props);
  }

  render(){
    return (
      <div id="tribute-container">
        <Back/>
        <main id="tribute-main">
          <h1 id="tribute-title">A Tribute to Superman(v10.1)</h1>
          <div id="tribute-img-div">
            <img src="https://www.dccomics.com/sites/default/files/GalleryChar_1900x900_allstarSuperman_52ab8fc670d367.92768430.jpg" alt="Superman flying over a sunset" id="tribute-image"/>
            <p id="tribute-img-caption">The Man of Steel flying over the mediterranean</p><br/><br/>
          </div>
          <div id="tribute-info">
            <article id="tribute-art-1961" className="tribute-article"><b><time>1961</time></b> - We all remember the first time we lost the so-called "Man of Steel".  Remember when Lex Luthor cured cancer? Luthor convinced Superman he had cancer, so that Superman would have to see him for treatment.  When he went in, Luthor (to the shock of all humanity btw) blasted him with Kryptonite rays. Knowing that the world's greatest superhero was mortal spawned a huge upsurge in super crime, and the Russian government even tried to create their own super man by launching a man into space.</article><br/>
            <article id="tribute-art-1966" className="tribute-article"><b><time>1966</time></b> - The second time Superman died, it gave Zunial his record short lived place in history.  The kryptonite rays he used vanquished Superman, but unfortunately an "Android Superman" of Zunial's own making gave its life so that the real Superman could live.  Why must the villians always create their own weaknesses? I guess as long as they do, we stay safe.<br/><br/>It is also theorized that the Kryponite rays caused now famous screenwriter Gene Roddenberry to come up with the idea for <i>Star Trek</i></article><br/>
            <article id="tribute-art-1968" className="tribute-article"><b><time>1968</time></b> - It was a short two years before we lost our greatest protector once again.  It was again by the hand of Lex Luthor, who (having learned to take the simpler plans) poisoned Superman with Virus X.  Superman initiated the euthanasia debate when he decided to fly into a star instead of suffering for a month.  However, the friendly Flammbronians stopped him and cured him of the disease.  Luthor admitted that he did not take every alien race into account. Crime and hatred escalated again with yet another death of Superman, leading a period of extreme unrest in the US and the assassination of legendary Civil Rights advocate Martin Luther King Jr.</article><br/>
            <article id="tribute-art-1971" className="tribute-article"><b><time>1971</time></b> - As we all well knew by now, Superman is not invulnerable to magic. This became painfully clear when the now infamous Doctor Light mind controlled a Daily Planet reporter by the name of Clark Kent to bring him the "Satanstaff".  Kent succeeded and Doctor Light put the Man of Steel in a death-like state (kinda like a coma, but magic).  Fortunately for the world, Gotham City's "Batman" was able to break Superman free of his curse and together they stopped Doctor Light and destroyed the Satanstaff.  Walt Disney's theme park, which had just begun construction, was hit in the fight and was instantly constructed exactly to Disney's imagination.  It to this day remains the most magical place on Earth.</article><br/>
            <article id="tribute-art-1977" className="tribute-article"><b><time>1977</time></b> - At the peak of the original Justice League's success, there came a super villian known as Count Crystal.  He made a pact with a demon (which exist btw) to destroy the Justice League in exchange for infinite power.  He killed Superman first, giving the rest of the Justice League little to no chance.  However, thanks to some quick thinking by Phantom Stranger, the demon was unable to consume Superman's spirit and got the demon to kill Count Crystal instead.  The energy created by the Justice League escaping their certain dooms drain the New York City power grid and caused the famous 1977 blackout.</article><br/>
            <article id="tribute-art-1986" className="tribute-article"><b><time>1986</time></b> - In the height of the cold war, Superman made the ultimate sacrifice for his adopted country.  Knowing it would strip him of his powers, he walked into a yellow Kryptonite chamber in the Russian controlled city of Chernobyl to cause it to melt down.  Unfortunately, it killed nearly 4000 people, but I'm sure our noble savior didn't see that coming.</article><br/>
            <article id="tribute-art-1992" className="tribute-article"><b><time>1992</time></b> - Metropolis residents more than anyone remember the original fight between Superman and Doomsday.  It scarred the city in a way it still hasn't recovered from (partly because of the numerous other fights in which Doomsday was involved).  Superman saved metropolis from complete destruction by killing doomsday, but died himself in the process.  For some reason, Pulitzer Prize winning journalist Lois Lane was by his side when he died.  Not only was Metropolis affected, but, when Doomsday threw Superman down from space he landed on a Chicago tunnel and caused the greates flood in Chicago history.</article><br/>
            <article id="tribute-art-1999" className="tribute-article"><b><time>1999</time></b> - We only consider this event as one death for simplicty purposes, but when the little known William Matthews (better know as Gog (Ikr)) was granted superpowers, including the ability to travel back in time.  He easily killed Superman, and then traveled back in time a day at a time to kill him again and again.  We all remeber the deaths of superman, even though they happened in backwards order, but we won't dwell on that.  It is hypothesized that Gog's real motivation was to go back in time and buy a stock portfolio before the DOW Jones hit a record high, and that superman caught on and tried to stop him (some conspiracy theorists think he wanted to be the only one who took advantage of it).</article><br/>
            <article id="tribute-art-2008" className="tribute-article"><b><time>2008</time></b> - Superman was one year away from a record 10 years without dying and once again, billionaire Lex Luthor attempted to kill Superman, but this time he learned from his mistakes in the previous two attempts.  Third times the charm (or so they say).  He gave HIMSELF superpowers and took on Superman toe-to-toe (okay maybe not the smartest).  Fortunately for Luthor, the sun was also shrinking and Superman decided that humanity was more important than his life, as always.  He flew straight to the sun and used his own energy to keep it alive.  Unfortunately, some bankers were planning on the Earth being frozen, resulting in one of the greatest financial crises in US history.</article><br/>
            <article id="tribute-art-2016" className="tribute-article"><b><time>2016</time></b> - The most recent death of Superman happened again at the hands of the 4-time-superman-killing champion Lex Luthor.  Luthor, always improving his dastardly plans, decided this time to distract Superman with a villanously positioned Batman, while at the same time recreating the horror Doomsday, who has succeeded in killing Superman before.  While most of Metropolis is again destroyed in the fight, Womder Woman and Batman were able to hold off Doomsday long enough for Superman to drive a Kryptonite spear into him, destroying them both.  Something tells me Superman will be back though. (Update: <time dateTime="true">11/15/17</time> - Superman is alive again because the Justice league resurrected him with a motherbox.)</article><br/>
            <a id="tribute-link" target="_blank" href="https://screenrant.com/times-superman-has-died-best-fake-deaths/">See the full article</a>
          </div>
        </main>
      </div>
    )
  }
}

export default Tribute;
